/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Chip: typeof import('primevue/chip')['default']
    ColorPicker: typeof import('primevue/colorpicker')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    CreateGameDialog: typeof import('./src/components/CreateGameDialog.vue')['default']
    DataView: typeof import('primevue/dataview')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Form: typeof import('@primevue/forms/form')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    Password: typeof import('primevue/password')['default']
    PlayerEditDialog: typeof import('./src/components/PlayerEditDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    TickTacToeGameView: typeof import('./src/components/games/tic-tac-toe/TickTacToeGameView.vue')['default']
    TickTacToeSettings: typeof import('./src/components/games/tic-tac-toe/TickTacToeSettings.vue')['default']
    Toast: typeof import('primevue/toast')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
